language: ruby
rvm: 
  - 2.2.3
env:
  - DB=postgresql

deploy:
  provider: heroku
  app: forestcitysite
  api_key: "2e41313d-e1ec-40e6-8e8e-b146d77581d7"
  run:
    - "bundle"
    - "rake db:migrate"
  strategy: git